name: eventure
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Genellikle bu şekilde bir aralık belirtmek daha iyidir

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4 
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.1.0
  get: ^4.7.2
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Sürümü güncelleyebilirsiniz

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/